### Dev (staging server) Stack
services:
  app:
    image: ${DOCKER_REGISTRY:-}aningcall-backend:${VERSION:-latest}
    container_name: aningcall-app-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=${DB_URL?required}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME?required}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD?required}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD:-devredis}
      - JWT_SECRET=${JWT_SECRET?required}
      - LOGGING_FILE_NAME=/app/logs/app.log
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - aningcall-network
    volumes:
      - ../../logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: aningcall-redis-dev
    command: redis-server --requirepass devredis --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    networks:
      - aningcall-network
    restart: unless-stopped

networks:
  aningcall-network:
    external: true

volumes:
  redis_data:
    driver: local
