name: Monthly Certbot Renew

on:
  schedule:
    - cron: '0 4 1 * *'  # Run at 04:00 UTC on the 1st of every month
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Renew certificates via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ${{ secrets.REMOTE_PATH }}
            # Run certbot renew using the shared webroot and volumes
            docker compose -f docker/compose/prod.yml run --rm certbot renew --webroot -w /var/www/certbot || true
            # Reload Nginx to pick up renewed certificates
            docker compose -f docker/compose/prod.yml exec nginx nginx -s reload || true
